config/routes.rb
Reeker::Application.routes.draw do
  get "profiles/show"

  devise_for :users
  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
    get 'editregistration', to: 'devise/registrations#edit', as: :editregistration
    get 'newpassword', to: 'devise/passwords#create', as: :newpassword
    
  end

  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed
  root to: 'statuses#index'

  get '/:id', to: 'profiles#show'

end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :content, :user_id
  belongs_to :user
  
  validates :user_id, presence: true
  validates :content , presence: true,
                       length: { in: 4..500 }
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :statuses
    has_many :user_friendships
    has_many :friends, through: :user_friendships
   
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :profile_name
   validates :first_name, presence: true,
                           length: { in: 3..20 }
   
   validates :last_name, presence: true
   validates :profile_name, presence: true,
                            length: { in: 4..20 },
                            uniqueness: true,
                            format:  {with: /^[a-zA-Z0-9_-]+$/,
                                      message: 'format input correctly.'
                                     }

    
    def full_name
  	 first_name + " " + last_name
    end
    
    def gravatar_url
      stripped_email = email.strip
      downcased_email = stripped_email.downcase
      hash = Digest::MD5.hexdigest(downcased_email)
      "http://gravatar.com/avatar/#{hash}"
    end
end
 

app/models/user_friendship.rb
class UserFriendship < ActiveRecord::Base
  # attr_accessible :title, :body

  
  belongs_to :user
  belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'
  
  attr_accessible :user, :friend, :user_id, :friend_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find_by_profile_name(params[:id])
    if @user
      @statuses = @user.statuses.all
      render action: :show
    else
    render file: 'public/404', status: 404, formats: [:html]
    end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
    before_filter :authenticate_user!, only: [:new, :edit, :update, :create]
    
    
  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = current_user.statuses.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = current_user.statuses.find(params[:id])
    params[:status].delete(:user_id) if params[:status].has_key?(:user_id)

    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = Status.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
  module ApplicationHelper

  	def flash_class(type)
  		case type
  		when :alert
  			"alert-danger"
  		when :notice
  			"alert-success"
  		else
  			""
  		end
  	end
  end
  

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reeker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
 
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        <li><%= link_to 'All Statuses',statuses_path %></li>
 
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
          
        	<% if user_signed_in? %>
						<li><%= link_to current_user.full_name, edit_user_registration_path %></li>
						<li><%= link_to "Log Out", logout_path %><li>
					<% else %>
						<li><%= link_to "New To Reeker", register_path %></li>
						<li><%= link_to "Log in", login_path %></li>
					<% end %>
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span          class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
              <% if user_signed_in? %>
            <li><%= link_to "Edit Account", edit_user_registration_path %></li>
               <li><%= link_to "Edit Password", editregistration_path %></li>
              <% end %>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  
<div class = "container mainCon">
 <% flash.each do |type, message| %>
 			 <div class="alert <%= flash_class type %> text-center" role ="alert" >
				 
				  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
 				  <%= message %>
 			</div>
 		<% end %>
<%= yield %>
</div>
          
</body>
</html>

app/views/profiles/show.html.erb
<div class="page-header">
  
  <h3 class="text-muted headfont" ><%= @user.full_name%></h3>
</div>


<div class ="well">
<% @statuses.each do |status| %>

<div class="status">
  
  <p class="paraFont"><%= status.content %></p>
  <div class="meta">
    <%= link_to time_ago_in_words(status.created_at) + " ago", status %> 
   </div>
<% end %>
</div>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: {class: "form-horizontal"}) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  

 
  <div class="mar"> <%= f.input :content %></div>
  
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<div class="page-header">
  <div class = "pull-right"><%= link_to "Post a New Status", new_status_path, class: "btn btn-success" %>
  </div>
  <h3 class="text-muted headfont" >All of the Statuses</h3>
</div>



<% @statuses.each do |status| %>
<div class="status">
	<div class = "row">
		
  <div class = "container">
		<div class = "col-md-1 imageSpacing">
		
			<%= image_tag status.user.gravatar_url %>
		</div>
		
	<div class = "col-md-7">
  <h3 class="nameFont lead text-muted"><%= status.user.full_name %></h3>
  <p class="paraFont"><%= status.content %></p>
  <div class="meta">
    <%= link_to time_ago_in_words(status.created_at) + " ago", status %> 
    <span class="admin">
        <div class="btn-group" role="group" aria-label="...">
        <button type="button" class="btn btn-default"> <%= link_to "Edit", edit_status_path(status) %></button>
        <button type="button" class="btn btn-default"> <%= link_to "Delete", status, method: :delete, data: { confirm: "Are you sure            your want to delete this status?"} %></button>
        </div>
    </span>
  </div>
  
</div>

</div>

</div>
</div>
<% end %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
    <%= @status.user.full_name %>

</p>

<p>
  <b>Content:</b>
  <%= @status.content %>
</p>


<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>